# nginx proxy address - http://172.17.0.1:8091

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - homer
    ports:
      - "8091:8091"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/homer:/config
      - ./rootfs/data/homer:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  homer:
    external: false
